### ISSUE TITLE
Binary

### ISSUE THREAD

**Issue by phobos2077** [Dustin32bit/BatchPropertyEditor#1]
Could you please provide working binaries for this util? I really want to try it out but provided binaries doesn't work on my system (win 7 x64).

**Comment by Dustin32bit** [comment]
It's been a hot minute, but I'll take a look to see if I still have this
thing sitting around somewhere.

**Comment by Dustin32bit** [comment]
I took a look, and it still works fine for me. It's likely that you are
either missing a .dll required for the GUI I used, or have your system
configured in some way that differs from mine. As it is, it works fine for
me, so I cannot really track down the problem at the moment.

**Comment by phobos2077** [comment]
Never mind. I've created my own WinForms .NET application using some of your functions code as a reference. It has less features but does what I want. 3 hour work just to be able to reduce fire distance for all weapons at once :D
[A link](https://yadi.sk/d/IrYB0n2evgnFY) if you're interested.
